language: java
jdk: openjdk8
cache:
    directories:
    - $HOME/.m2
# tests will be executed at cobertura phases
script:
    - mvn install -DskipTests
    - mvn cobertura:cobertura
after_success:
    - bash <(curl -s https://codecov.io/bash)