language: java
jdk: openjdk8
cache:
    directories:
    - $HOME/.m2
install:
    - pip install --user codecov
script: mvn install
after_success:
    - bash <(curl -s https://codecov.io/bash) -v -f target/site/cobertura/coverage.xml