language: java
jdk: openjdk8
cache:
    directories:
    - $HOME/.m2
script:
    - mvn install
    - mvn cobertura:cobertura
after_success:
    - bash <(curl -s https://codecov.io/bash) -v -f target/site/cobertura/coverage.xml